// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQk1lykPG8OLn-zvwdxRWkX-0mCyN6bO0',
    appId: '1:508814058583:web:9ce8dbdf8b2d7e9840af12',
    messagingSenderId: '508814058583',
    projectId: 'ebook-7e0a5',
    authDomain: 'ebook-7e0a5.firebaseapp.com',
    storageBucket: 'ebook-7e0a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQk1lykPG8OLn-zvwdxRWkX-0mCyN6bO0',
    appId: '1:508814058583:android:9ce8dbdf8b2d7e9840af12',
    messagingSenderId: '508814058583',
    projectId: 'ebook-7e0a5',
    storageBucket: 'ebook-7e0a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQk1lykPG8OLn-zvwdxRWkX-0mCyN6bO0',
    appId: '1:508814058583:ios:9ce8dbdf8b2d7e9840af12',
    messagingSenderId: '508814058583',
    projectId: 'ebook-7e0a5',
    storageBucket: 'ebook-7e0a5.firebasestorage.app',
    iosBundleId: 'com.example.ebooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQk1lykPG8OLn-zvwdxRWkX-0mCyN6bO0',
    appId: '1:508814058583:macos:9ce8dbdf8b2d7e9840af12',
    messagingSenderId: '508814058583',
    projectId: 'ebook-7e0a5',
    storageBucket: 'ebook-7e0a5.firebasestorage.app',
    iosBundleId: 'com.example.ebooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQk1lykPG8OLn-zvwdxRWkX-0mCyN6bO0',
    appId: '1:508814058583:windows:9ce8dbdf8b2d7e9840af12',
    messagingSenderId: '508814058583',
    projectId: 'ebook-7e0a5',
    storageBucket: 'ebook-7e0a5.firebasestorage.app',
  );
} 